@host = http://localhost:4444/api/auth/signup

GET {{host}}/

###
POST {{host}}/
Content-Type: application/json

{
	"username": "ryan",
	"email": "ryan@ibm.com",
	"password": "password",
	"roles": [
		"admin",
		"moderator"
	]
}